services:
  node-backend:
    build:
      context: ./nodeJSBackend
      dockerfile: Dockerfile
    volumes:
      - ./nodeJSBackend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./nodeJSBackend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
