services:
  node-backend:
    build:
      context: ./nodeJSBackend
      dockerfile: Dockerfile
    volumes:
      - ./nodeJSBackend:/usr/src/app
      - /app/public
    ports:
      - '3001:3001'
    env_file:
      - ./nodeJSBackend/.env

  cb-app-frontend:
    build:
      context: ./cb-app-frontend
      dockerfile: Dockerfile
    volumes:
      - ./cb-app-frontend:/app/
      - /app/node_modules
    ports:
      - '5175:5175'
    env_file:
      - ./cb-app-frontend/.env

  cb-lp-frontend:
    build:
      context: ./cb-lp-frontend
      dockerfile: Dockerfile
    volumes:
      - ./cb-lp-frontend:/app/
      - ./cb-lp-frontend/node_modules:/app/node_modules
    ports:
      - '5174:5174'
    env_file:
      - ./cb-lp-frontend/.env

volumes:
  node_modules:
  node_modules_frontend:
  public:
    driver: local
