# version: "3.8"

services:
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: chat_with_us
  #     POSTGRES_USER: mecha
  #     POSTGRES_PASSWORD: mecha
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # mongo:
  #   image: mongo:latest
  #   logging:
  #     driver: none
  #   ports:
  #     - '27018:27017'
  #   volumes:
  #     - mongo-data:/data/db

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend:/app/backend
  #   depends_on:
  #     - db
  #   ports:
  #     - '8000:8000'

  node-backend:
    build:
      context: ./nodeJSBackend
      dockerfile: Dockerfile
    volumes:
      - ./nodeJSBackend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    # depends_on:
    #   - mongo
    # env_file:
    #   - ./nodeJSBackend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/frontend:/app/frontend
    ports:
      - '5170:5170'
# volumes:
#   postgres_data:
#   mongo-data:
