version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chat_with_us
      POSTGRES_USER: mecha
      POSTGRES_PASSWORD: mecha
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/frontend:/app/frontend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
